---
title: "test_1"
author: "Maxim_Nest"
date: '8 апреля 2017 г '
output: html_document
---

```{r setup, warning=FALSE, message=FALSE}

library(DESeq2)
library(ggplot2)
library(pheatmap)
library(amap)
library(dbscan)
options(width=120)
library(dplyr)

```

```{r read_tables, warning=FALSE, error=FALSE, message=FALSE}

conditions <- read.csv("GSE89633_conditions.tsv", sep="\t", row.names=1)
counts <- read.csv("GSE89633_counts.tsv", sep = "\t", row.names=1)

```


```{r PCA, warning=FALSE, error=FALSE, message=FALSE}

dds <- DESeqDataSetFromMatrix(countData = counts,
                              colData = conditions,
                              design = ~ cells + conditions)
dds <- dds[rowSums(counts(dds)) > 20, ]
dds <- DESeq(dds)
vst_dds <- vst(dds)
counts.norm <- assay(vst_dds)

pca_data <- prcomp(t(counts.norm))
percents <- pca_data$sdev^2 / sum(pca_data$sdev^2)
to_plot <- t(counts.norm) %*% pca_data$rotation


data_for_vis <- data.frame(
  x=to_plot[, 1],
  y=to_plot[, 2],
  cells=conditions[, 1],
  condition=conditions[, 2],
  name=rownames(conditions)
)

viz <- ggplot(data=data_for_vis, aes(x=x, y=y, color=cells, shape=condition, text=name)) +
  geom_point(size=3) + theme_bw()  +
  xlab(paste0("PC", 1, ": ", formatC(100 * percents[1], digits=4), "%")) +
  ylab(paste0("PC", 2, ": ", formatC(100 * percents[2], digits=4), "%")) 

#+ geom_text(alpha=1, size=3, aes(label=data_for_vis$name))
  
viz

```

```{r top_8000, warning=FALSE, message=FALSE, error=FALSE}

dds_top <- DESeqDataSetFromMatrix(countData = counts,
                              colData = conditions,
                              design = ~ cells + conditions)

dds_top <- dds_top[rowSums(counts(dds_top)) > 20, ]
dds_top <- dds_top[order(rowSums(counts(dds_top)), decreasing = T), ]
# 8000 genes
dds_top <- head(dds_top, 8000)
# create object
dds_top <- DESeq(dds_top)

# log expression
log_exp <- assay(rlog(dds_top))
# clusters
clusters <- Kmeans(log_exp, 9, method="correlation", iter.max = 20000)
#unique(clusters$cluster)

# clusters, as factor for pheatmap
cluster_df <- as.data.frame(clusters$cluster)
colnames(cluster_df) <- "cluster"
cluster_df$cluster <- as.factor(cluster_df$cluster)

# order data for heatmap

order_data <- log_exp[order(clusters$cluster), 
                        order(conditions$conditions, conditions$cells)]

order_data <- t(apply(order_data, 1, function(r) {
  (r - min(r)) / (max(r) - min(r))
}))


# heatmap
#png("heatmap_ordered_data.png", width=6, height=20, units="in", res=300)

pheatmap(order_data, 
         show_rownames = F, 
         cluster_rows = F, 
         cluster_cols = F,
         annotation_col = conditions, annotation_row = cluster_df)
#dev.off()


```

### Ответы на вопросы:
1) Нет, ни по PCA(четкие группы), ни по heatmap явных выбросов не видно
2) Нет, каждая группа включает клетки одного типа, но при разных условиях (нокаут, WT) - поэтому рудно предположить, что объясняет большую часть вариации

```{r warning=FALSE, message=FALSE, error=FALSE}
#conditions
cond_FB <- conditions[conditions$cells=="cell type: FB", ]
cond_FAP <- conditions[conditions$cells=="cell type: FAP",]
cond_SMP <- conditions[conditions$cells=="cell type: SMP",]
#counts
counts_FB <- counts[, row.names(cond_FB)]
counts_FAP <- counts[, row.names(cond_FAP)]
counts_SMP <- counts[, row.names(cond_SMP)]

####DESeq 
# FB
dds_FB <- DESeqDataSetFromMatrix(countData = counts_FB,
                              colData = cond_FB,
                              design = ~ conditions + conditions)
dds_FB <- dds_FB[rowSums(counts(dds_FB)) > 20, ]
dds_FB <- DESeq(dds_FB)

# FAP
dds_FAP <- DESeqDataSetFromMatrix(countData = counts_FAP,
                              colData = cond_FAP,
                              design = ~ conditions + conditions)
dds_FAP <- dds_FAP[rowSums(counts(dds_FAP)) > 20, ]
dds_FAP <- DESeq(dds_FAP)

# SMP

dds_SMP <- DESeqDataSetFromMatrix(countData = counts_SMP,
                              colData = cond_SMP,
                              design = ~ conditions + conditions)
dds_SMP <- dds_SMP[rowSums(counts(dds_SMP)) > 20, ]
dds_SMP <- DESeq(dds_SMP)

# results

res_FB <- results(dds_FB)
res_FAP <- results(dds_FAP)
res_SMP <- results(dds_SMP)

# for volcano

FB_cond <- data.frame(
  x=res_FB$log2FoldChange,
  y=-log10(res_FB$padj),
  Significant=ifelse(res_FB$padj < 0.01, "significant", "not significant"),
  design_type="FB-WT vs FB-DKO"
)

FAP_cond <- data.frame(
  x=res_FAP$log2FoldChange,
  y=-log10(res_FAP$padj),
  Significant=ifelse(res_FAP$padj < 0.01, "significant", "not significant"),
  design_type="FAP-WT vs FAP-DKO"
)

SMP_cond <- data.frame(
  x=res_SMP$log2FoldChange,
  y=-log10(res_SMP$padj),
  Significant=ifelse(res_SMP$padj < 0.01, "significant", "not significant"),
  design_type="SMP-WT vs SMP-DKO"
)

# volcano plots

merged_designs <- rbind(FB_cond, FAP_cond, SMP_cond)
                        
ggplot(merged_designs, aes(x=x, y=y, colour = factor(Significant))) +
  geom_point(size=1) + theme_bw()+
  facet_grid(. ~ design_type) +
  scale_color_manual(values = c("significant" = "red", "not significant" = "black"))+
  geom_hline(yintercept = -log10(0.01), colour = "red") +
  xlab("Log fold change")+
  ylab("Adjusted p.value")

#### Venn
# df
df_FB <- as.data.frame(res_FB)
df_FAB <- as.data.frame(res_FAP)
df_SMP <- as.data.frame(res_SMP)

diffExpGenes_FB <- df_FB[which(df_FB$padj < 0.01), ]
diffExpGenes_FAB <- df_FAB[which(df_FAB$padj < 0.01), ]
diffExpGenes_SMP <- df_SMP[which(df_SMP$padj < 0.01), ]


```


